// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcAsusFWYsNAYqQIHMAovIChkHeQ6vd00',
    appId: '1:109015641118:web:b23ca103c9a53166d7120f',
    messagingSenderId: '109015641118',
    projectId: 'darshana-2f4a7',
    authDomain: 'darshana-2f4a7.firebaseapp.com',
    storageBucket: 'darshana-2f4a7.firebasestorage.app',
    measurementId: 'G-5FJTRHRRRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbbV0VvQKCfZlVfX3hoRPz-_aClhQZm4',
    appId: '1:109015641118:android:48d3cab0f491ae61d7120f',
    messagingSenderId: '109015641118',
    projectId: 'darshana-2f4a7',
    storageBucket: 'darshana-2f4a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7IsHB9jLvHO9jVBLfsq4ph5CvG60r3PQ',
    appId: '1:109015641118:ios:edb7e36aa3b04706d7120f',
    messagingSenderId: '109015641118',
    projectId: 'darshana-2f4a7',
    storageBucket: 'darshana-2f4a7.firebasestorage.app',
    iosClientId: '109015641118-h5033lqk7ib2a6jb10p08d9kb24hgs29.apps.googleusercontent.com',
    iosBundleId: 'com.indiadarshana.app',
  );
}
